# Generated by Django 4.2.7 on 2023-11-19 04:21

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('coffee', '0002_rename_flovour_flavour_rename_flovour_coffee_flavour'),
    ]

    operations = [
        migrations.AlterField(
            model_name='coffee',
            name='name',
            field=models.CharField(max_length=100),
        ),
    ]
